language: node_js
deploy:
  - provider: npm
    email: $NPME
    api_key: $NPMP
    on:
      tags: true
  - provider: npm
    email: $NPME
    api_key: $NPMP
    tag: canary
    on:
      branch: master
      tag: canary
